### ISSUE TITLE
the legend returns :D 

### ISSUE THREAD

**Issue by dlevi309** [qwertyuiop1379/qd#1]
I know this is highly irregular, and forgive me if this is pushing it, but since your twitter is gone + and I’m not sure if I’m ever gonna get another chance to ask, do you happen to still have the source code to bongwater?

**Comment by dlevi309** [comment]
and again, I’m sorry for ambushing you with this as a github issue :p if you wanted to close this out upon seeing it, I wouldn’t hold it against you! Big fan of your work, and I hope everything else is going well with your other endeavors since leaving the JB community 👍

**Comment by objc-class** [comment]
Missing SwipeExtenderX :D

**Comment by qwertyuiop1379** [comment]
@dlevi309 Hi, I do still have the source code. I'll put it on my Tweaks repository today.
@objc-class Me too man, I haven't had a jailbroken phone in ages now

**Comment by dlevi309** [comment]
thanks man :D (btw, I saw that you uploaded it, but Tweak.x seems to be a compiled binary)

**Comment by qwertyuiop1379** [comment]
@dlevi309 my hard drive was corrupted a while back and I lost a large amount of data. It looks like unfortunately the Tweak.x file was also corrupted, so I'll see if I can find a backup anywhere

**Comment by dlevi309** [comment]
@qwertyuiop1379 gotcha, that’s a shame, but either way thank you :)
